---
- name: Fetch Docker-compose version
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false
  failed_when: false

- name: Delete if outdated
  file:
    path: /usr/local/bin/docker-compose
    state: absent
  when: >
    docker_compose_version.stdout is defined
    and '1.28.5' not in docker_compose_version.stdout

- name: Install Docker Compose.
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755